SD-340-W22SD-2021-2022 - Final Project 2/Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SD_340_W22SD_2021_2022___Final_Project_2.Models
{
    public class Project
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [MinLength(5, ErrorMessage = "Name must be at least 5 characters long.")]
        [MaxLength(200, ErrorMessage = "Name must be less than or equal to 200 characters.")]
        public string Name { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; } = new HashSet<Ticket>();

        [InverseProperty("Projects")]
        public virtual ICollection<ApplicationUser> Developers { get; set; } = new HashSet<ApplicationUser>();
    }
}

SD-340-W22SD-2021-2022 - Final Project 2/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SD_340_W22SD_2021_2022___Final_Project_2.BLL;
using SD_340_W22SD_2021_2022___Final_Project_2.DAL;
using SD_340_W22SD_2021_2022___Final_Project_2.Data;
using SD_340_W22SD_2021_2022___Final_Project_2.Models;
using SD_340_W22SD_2021_2022___Final_Project_2.Models.ViewModels;

namespace SD_340_W22SD_2021_2022___Final_Project_2.Controllers
{
    public class CommentController : Controller
    {
        private readonly CommentBusinessLogic commentBL;
        private readonly TicketBusinessLogic ticketBL;
        private readonly UserBusinessLogic userBL;
        private readonly UserManager<ApplicationUser> _userManager;

        public CommentController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            commentBL = new CommentBusinessLogic(new CommentRepository(context));
            ticketBL = new TicketBusinessLogic(new TicketRepository(context));
            userBL = new UserBusinessLogic(userManager);
            _userManager = userManager;
        }

        public async Task<IActionResult> CommentsForTask(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            CreateCommentViewModel vm;
            List<Comment>? comments;
            Comment newComment = new Comment();

            try
            {
               comments = commentBL.GetAllCommentsByTicket(ticketId);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Project");
            }

            newComment.TicketId = ticketId;
            vm = new CreateCommentViewModel(comments, newComment);

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles="Developer")]
        public async Task<IActionResult> Create([Bind("Id, Content, TicketId, Ticket, UserId, User")] Comment NewComment)
        {
            try
            {
                bool taskOwners = true;
                bool taskWatchers = true;

                ApplicationUser currentUser = userBL.GetCurrentUserByName(User.Identity.Name);
                Ticket checkTicket = ticketBL.FindTicketById(NewComment.TicketId);

                if (checkTicket.TaskOwners.FirstOrDefault(to => to.Id == currentUser.Id) == null)
                {
                    taskOwners = false;
                }

                if (checkTicket.TaskWatchers.FirstOrDefault(to => to.Id == currentUser.Id) == null)
                {
                    taskWatchers = false;
                }

                if (!taskOwners && !taskWatchers)
                {
                    return Unauthorized("Only task owners and task watchers can add comments to this task");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Project");
            }

            try
            {
                ApplicationUser user = userBL.GetCurrentUserByName(User.Identity.Name);

                Ticket ticket = ticketBL.FindTicketById(NewComment.TicketId);

                commentBL.CreateAndSaveComment(NewComment, ticket, user);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Project");
            }

            return RedirectToAction("CommentsForTask", new { ticketId = NewComment.TicketId });
        }
    }
}

SD-340-W22SD-2021-2022 - Final Project 2/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SD_340_W22SD_2021_2022___Final_Project_2.Data;
using SD_340_W22SD_2021_2022___Final_Project_2.Models;
using SD_340_W22SD_2021_2022___Final_Project_2.Models.ViewModels;
using SD_340_W22SD_2021_2022___Final_Project_2.BLL;
using SD_340_W22SD_2021_2022___Final_Project_2.DAL;

namespace SD_340_W22SD_2021_2022___Final_Project_2.Controllers
{
    public class ProjectController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ProjectBusinessLogic projectBL;
        private readonly UserBusinessLogic userBL;
        public ProjectController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            projectBL = new ProjectBusinessLogic(new ProjectRepository(context), _userManager);
            userBL = new UserBusinessLogic(_userManager);
        }

        [Authorize(Roles = "Project Manager, Developer")]
        public async Task<IActionResult> Index(string? hours, string? priority, bool? completed)
        {
            List<Project>? projects = null;

            try
            {
                ApplicationUser user = userBL.GetCurrentUserByName(User.Identity.Name);
                List<string> roles = await userBL.GetUserRoles(user);
                string role = roles.Find(r => r.Equals("Developer"));
                if (role == null)
                {
                    role = roles.Find(r => r.Equals("Project Manager"));
                }
                if (role.Equals("Developer"))
                {
                    projects = await projectBL.GetAllProjectsByDeveloperAsync(user.Id);
                }

                if (role.Equals("Project Manager"))
                {
                    projects = projectBL.GetAllProjects();
                }

                //Abstract into helper method for unit testing.
                if (hours == "asc")
                {
                    projects.ForEach(p =>
                    {
                        p.Ticket = p.Ticket.OrderBy(t => t.Hours).ToList();
                    });
                }
                else if (hours == "desc")
                {
                    projects.ForEach(p =>
                    {
                        p.Ticket = p.Ticket.OrderByDescending(t => t.Hours).ToList();
                    });
                }
                else if (priority == "asc")
                {
                    projects.ForEach(p =>
                    {
                        p.Ticket = p.Ticket.OrderBy(t => t.Priority).ToList();
                    });
                }
                else if (priority == "desc")
                {
                    projects.ForEach(p =>
                    {
                        p.Ticket = p.Ticket.OrderByDescending(t => t.Priority).ToList();
                    });
                }


                return View(projects);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> Create()
        {
            List<ApplicationUser>? developers;
            CreateProjectViewModel vm;
            Project project = new Project();

            try
            {
                developers = await userBL.GetAllUsersWithSpecificRoleAsync("Developer");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }

            vm = new CreateProjectViewModel(project, developers);

            return View(vm);
        }

        [Authorize(Roles = "Project Manager")]
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id, Name, Ticket, Developers")] Project project, string[] developerIds)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                foreach (String developerId in developerIds)
                {
                    ApplicationUser dev = userBL.GetUserByUserId(developerId);
                    project.Developers.Add(dev);
                }
                projectBL.CreateProject(project);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult Details(int projectId)
        {
            Project project = projectBL.GetProjectDetails(projectId);
            if (project == null)
            {
                return NotFound();
            }
            List<Ticket> tickets = project.Ticket.ToList();
            List<ApplicationUser> developers = project.Developers.ToList();
            return View(project);
        }
    }
}

SD-340-W22SD-2021-2022 - Final Project 2/Controllers/TicketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SD_340_W22SD_2021_2022___Final_Project_2.BLL;
using SD_340_W22SD_2021_2022___Final_Project_2.DAL;
using SD_340_W22SD_2021_2022___Final_Project_2.Data;
using SD_340_W22SD_2021_2022___Final_Project_2.Models;
using SD_340_W22SD_2021_2022___Final_Project_2.Models.ViewModels;

namespace SD_340_W22SD_2021_2022___Final_Project_2.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        private readonly TicketBusinessLogic ticketBL;
        private readonly ProjectBusinessLogic projectBL;
        private readonly UserBusinessLogic userBL;
        private readonly UserManager<ApplicationUser> _userManager;

        public TicketController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            ticketBL = new TicketBusinessLogic(new TicketRepository(context));
            projectBL = new ProjectBusinessLogic(new ProjectRepository(context), userManager);
            userBL = new UserBusinessLogic(userManager);
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> Create(int projectId)
        {
            Project? project = projectBL.GetProjectById(projectId);

            if (project == null)
            {
                return BadRequest();
            }

            List<ApplicationUser>? developers = project.Developers.ToList();
            CreateTicketViewModel vm;
            Ticket ticket = new Ticket();

            vm = new CreateTicketViewModel(project, ticket, developers);

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> Create(
            [Bind("Id, Completed, Name, Hours, Priority, ProjectId, Project")] Ticket ticket,
            int projectId, string[] taskOwnerIds, Priority priority = Priority.low)
        {
            //This returns invalid because ModelState.Project is null
            //if (!ModelState.IsValid)
            //{
            //    return RedirectToAction("Create", new { projectId = projectId });
            //}

            ApplicationUser dev = new ApplicationUser();

            if (taskOwnerIds.Count() == 0)
            {
                return RedirectToAction("Create", new { projectId = projectId });
            }

            foreach (string taskOwnerId in taskOwnerIds)
            {
               dev = await _userManager.FindByIdAsync(taskOwnerId);
            }

            ticketBL.CreateAndSaveTicket(ticket, priority, projectId, taskOwnerIds, dev);


            return RedirectToAction("Index", "Project");
        }

        [HttpPost]
        public async Task<IActionResult> ToggleTicket(int projectId, int ticketId)
        {
            try
            {
                ApplicationUser currentUser = userBL.GetCurrentUserByName(User.Identity.Name);
                Ticket ticket = ticketBL.FindTicketById(ticketId);

                if (ticket.TaskOwners.FirstOrDefault(to => to.Id == currentUser.Id) == null)
                {
                    return Unauthorized("Only developers who are a task owner of this project can mark a task as complete");
                }

                ticket.Completed = !ticket.Completed;

                ticketBL.UpdateTicket(ticket);
                ticketBL.SaveTicket();

                return RedirectToAction("Details", "Project", new { projectId = projectId });
            }
            catch (Exception ex)
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ChangeRequiredHours(int projectId, int ticketId, int hours)
        {
            try
            {
                ApplicationUser currentUser = userBL.GetCurrentUserByName(User.Identity.Name);
                Ticket ticket = ticketBL.FindTicketById(ticketId);

                if (ticket.TaskOwners.FirstOrDefault(to => to.Id == currentUser.Id) == null)
                {
                    return Unauthorized("Only developers who are a task owner of this project can adjust required hours of a task");
                }

                ticket.Hours = hours;

                ticketBL.UpdateTicket(ticket);
                ticketBL.SaveTicket();

                return RedirectToAction("Details", "Project", new { projectId = projectId });
            }
            catch (Exception ex)
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddToWatchList(int projectId, int ticketId)
        {
            try
            {
                ApplicationUser currentUser = userBL.GetCurrentUserByName(User.Identity.Name);
                Project project = projectBL.GetProjectById(projectId);
                Ticket ticket = ticketBL.FindTicketById(ticketId);

                if (project.Developers.FirstOrDefault(d => d.Id == currentUser.Id) == null)
                {
                    return Unauthorized("Only developers assigned to this project can watch the tasks");
                }

                ticketBL.AddOrRemoveWatcher(ticket, currentUser);

                ticketBL.UpdateTicket(ticket);
                ticketBL.SaveTicket();

                return RedirectToAction("Details", "Project", new { projectId = projectId });
            }
            catch (Exception ex)
            {
                return BadRequest();

            }
        }
    }
}

SD-340-W22SD-2021-2022 - Final Project 2/Views/Project/Create.cshtml
@using SD_340_W22SD_2021_2022___Final_Project_2.Models.ViewModels;

@model CreateProjectViewModel;

<h2>Create New Project</h2>
<form class="form" asp-action="Create" asp-controller="Project" method="post">
    <label class="form-label" asp-for="Project.Name"></label>
    <input class="form-control" asp-for="Project.Name" />
    <div>
        <span asp-validation-for="Project.Name" class="text-danger"></span>
    </div>
    <hr />

    <h6>Assign Developers</h6>
    @foreach (ApplicationUser developer in @Model.Developers)
    {
        <div>
            <input type="checkbox" id="developerIds" name="developerIds" value="@developer.Id">
            <label for="developerIds">@developer.UserName</label>
        </div>
    }

    <hr />

    <button type="submit">Create Project</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SD-340-W22SD-2021-2022 - Final Project 2/Views/Project/Details.cshtml
@model SD_340_W22SD_2021_2022___Final_Project_2.Models.Project

<h1>@Model.Name</h1>

<hr />

<h4>Tasks</h4>

@foreach (Ticket ticket in Model.Ticket)
{
    <h3>@ticket.Name</h3>
    <div><b>Priority</b> @ticket.Priority </div>
    <div><b>Required Hours</b> @ticket.Hours</div>
    <div><b>Status</b>
    @if (ticket.Completed)
    {
        <span>Completed</span>
    }
    else
    {
        <span>Not Completed</span>
    }
    </div>
    <a asp-action="CommentsForTask" asp-controller="Comment" asp-route-ticketId="@ticket.Id">Comments</a>

    <form class="project-form-button" asp-action="AddToWatchList" asp-controller="Ticket" asp-route-projectId="@Model.Id" asp-route-ticketId="@ticket.Id" method="post">
        <button type="submit">
            @if (ticket.TaskWatchers.FirstOrDefault(tw => tw.UserName == User.Identity.Name) == null)
            {
                <span class="material-symbols-outlined">visibility</span>
                <span>Start Watching</span>
            }
            else
            {
                <span class="material-symbols-outlined">visibility_off</span>
                <span>Stop Watching</span>
            }
        </button>
    </form>
    <form class="project-form-button" asp-action="ToggleTicket" asp-controller="Ticket" method="post" asp-route-projectId="@Model.Id" asp-route-ticketId="@ticket.Id">
        @if (!ticket.Completed)
        {
            <button type="submit">Mark it as complete</button>

        }
        else
        {
            <button type="submit">Mark it as not complete</button>
        }
    </form>
    <form class="project-form-button" asp-action="ChangeRequiredHours" asp-controller="Ticket" method="post" asp-route-projectId="@Model.Id" asp-route-ticketId="@ticket.Id">
        <input type="number" name="hours" />
        <button type="submit">Adjust Required Hours</button>
    </form>
    <hr />
}


<h2>Assigned Developers</h2>
<ul>
    @foreach (ApplicationUser developer in Model.Developers)
    {
        <li>@developer.UserName</li>
    }
</ul>

SD-340-W22SD-2021-2022 - Final Project 2/Views/Project/Index.cshtml
@model IEnumerable<SD_340_W22SD_2021_2022___Final_Project_2.Models.Project>

<h1>List of Projects</h1>

<a class="btn btn-primary" asp-action="Create" asp-controller="Project">Create</a>

<hr />

@*Bootstrap code comes from https://getbootstrap.com/docs/5.0/components/buttons/#block-buttons*@
<div class="d-grid gap-2 d-md-block">
    <a class="btn btn-primary btn-sm" asp-action="Index" asp-controller="Project" asp-route-hours="asc" asp-route-completed="@Context.Request.Query["completed"]">
        Order By Hours Ascending
    </a>
    <a class="btn btn-primary btn-sm" asp-action="Index" asp-controller="Project" asp-route-hours="desc" asp-route-completed="@Context.Request.Query["completed"]">
        Order By Hours Descending
    </a>
    <a class="btn btn-primary btn-sm" asp-action="Index" asp-controller="Project" asp-route-priority="asc" asp-route-completed="@Context.Request.Query["completed"]">
        Order By Priority Ascending
    </a>
    <a class="btn btn-primary btn-sm" asp-action="Index" asp-controller="Project" asp-route-priority="desc" asp-route-completed="@Context.Request.Query["completed"]">
        Order By Priority Descending
    </a>
    @if (Context.Request.Query["completed"] == "True")
    {
        <a class="btn btn-primary btn-sm" asp-action="Index" asp-controller="Project" asp-route-hours="@Context.Request.Query["hours"]" asp-route-priority="@Context.Request.Query["priority"]" asp-route-completed="@false">
            Show Only Uncompleted
        </a>
    }
    else
    {
        <a class="btn btn-primary btn-sm" asp-action="Index" asp-controller="Project" asp-route-hours="@Context.Request.Query["hours"]" asp-route-priority="@Context.Request.Query["priority"]" asp-route-completed="@true">
            Show Only Completed
        </a>
    }
</div>

<hr />

@foreach (Project project in Model)
{
    <a asp-action="Details" asp-controller="Project" asp-route-projectId="@project.Id"><h4>@project.Name</h4></a>
    <a asp-action="Create" asp-controller="Ticket" asp-route-projectId="@project.Id">Add Task</a>
    @if (project.Ticket.Count > 0)
    {
        <ul>
            @foreach (Ticket ticket in project.Ticket)
            {
                <li>
                    @ticket.Name | @ticket.Priority | @ticket.Hours |
                    @if (ticket.Completed)
                    {
                        <span>Completed</span>
                    }
                    else
                    {
                        <span>In Progress</span>
                    }
                </li>
            }
        </ul>
    }
    else
    {
        <div>No tasks created for this project</div>
    }
    <hr />
}